baseURL = "https://example.com/"  # Replace with your domain
languageCode = "en-us"
title = "YoloInfinityHugp"
theme = []  # No external theme; using custom layouts

[pagination]
  pagerSize = 10

[params]
  description = "A personal blog and portfolio"
  author = "Your Name"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in Markdown

[markup.highlight]
  style = "monokai"  # For code syntax highlighting

enableRSS = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4