baseURL = "https://yoloinfinity55.github.io/hugo_tailwindcss_blog/"
languageCode = "en-us"
title = "YoloInfinityHugo"

[pagination]
  pagerSize = 10

# This enables the use of .Permalink and other page variables in your CSS, which is needed for Tailwind's JIT compiler.
[build]
  writeStats = true

[params]
  author = "Your Name"
  description = "A personal blog and portfolio"
  # Social links for the footer
  github = "https://github.com/yourusername"
  twitter = "https://x.com/yourusername"
  linkedin = "https://linkedin.com/in/yourusername"

# Main menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

# Markup configuration for Goldmark (the default Markdown renderer)
[markup]
  [markup.highlight]
    # This is a good default. It prevents Hugo from adding inline styles
    # to code blocks, which allows your Tailwind CSS to control the styling.
    noClasses = false
    # You can pick a different style here that fits your theme
    # Run `hugo gen chromastyles --style=monokai` to see a preview
    style = "monokai"